/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JournalEntry {
  'conquered' : string,
  'date' : string,
  'dominate' : string,
}
export interface Profile { 'weight' : string, 'goal' : string, 'name' : string }
export interface Stats {
  'xp' : bigint,
  'streak' : bigint,
  'lastCompletedDate' : string,
  'noExcuseMode' : boolean,
  'soundEnabled' : boolean,
}
export interface StrengthLog {
  'weight' : number,
  'date' : string,
  'reps' : string,
  'sets' : bigint,
  'exercise' : string,
}
export interface Task {
  'meditation' : boolean,
  'date' : string,
  'diet' : boolean,
  'sleep' : boolean,
  'workout' : boolean,
  'water' : boolean,
}
export interface UserData {
  'tasks' : Array<Task>,
  'journalEntries' : Array<JournalEntry>,
  'weightEntries' : Array<WeightEntry>,
  'stats' : Stats,
  'achievements' : Array<string>,
  'strengthLogs' : Array<StrengthLog>,
  'profile' : Profile,
}
export interface UserProfile {
  'weight' : string,
  'goal' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weight' : number, 'date' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllData' : ActorMethod<[], undefined>,
  'deleteJournalEntry' : ActorMethod<[string], undefined>,
  'deleteUserData' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserData>>,
  'getAllUsersAdmin' : ActorMethod<
    [],
    Array<
      {
        'streak' : bigint,
        'principal' : string,
        'name' : string,
        'journalCount' : bigint,
        'tasksCompleted' : bigint,
        'email' : string,
      }
    >
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getJournalEntries' : ActorMethod<
    [],
    Array<{ 'id' : string, 'content' : string, 'date' : string }>
  >,
  'getProgress' : ActorMethod<
    [],
    [] | [
      { 'streak' : bigint, 'lastUpdated' : string, 'tasksCompleted' : bigint }
    ]
  >,
  'getUser' : ActorMethod<[], [] | [{ 'name' : string, 'email' : string }]>,
  'getUserData' : ActorMethod<[], [] | [UserData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProgress' : ActorMethod<[bigint, bigint, string], undefined>,
  'saveUser' : ActorMethod<[string, string], undefined>,
  'saveUserData' : ActorMethod<[UserData], undefined>,
  'searchUserByName' : ActorMethod<[string], [] | [UserData]>,
  'updateUserStreak' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];