/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'meditation' : IDL.Bool,
  'date' : IDL.Text,
  'diet' : IDL.Bool,
  'sleep' : IDL.Bool,
  'workout' : IDL.Bool,
  'water' : IDL.Bool,
});
export const JournalEntry = IDL.Record({
  'conquered' : IDL.Text,
  'date' : IDL.Text,
  'dominate' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'date' : IDL.Text,
});
export const Stats = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'lastCompletedDate' : IDL.Text,
  'noExcuseMode' : IDL.Bool,
  'soundEnabled' : IDL.Bool,
});
export const StrengthLog = IDL.Record({
  'weight' : IDL.Float64,
  'date' : IDL.Text,
  'reps' : IDL.Text,
  'sets' : IDL.Nat,
  'exercise' : IDL.Text,
});
export const Profile = IDL.Record({
  'weight' : IDL.Text,
  'goal' : IDL.Text,
  'name' : IDL.Text,
});
export const UserData = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'journalEntries' : IDL.Vec(JournalEntry),
  'weightEntries' : IDL.Vec(WeightEntry),
  'stats' : Stats,
  'achievements' : IDL.Vec(IDL.Text),
  'strengthLogs' : IDL.Vec(StrengthLog),
  'profile' : Profile,
});
export const UserProfile = IDL.Record({
  'weight' : IDL.Text,
  'goal' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllData' : IDL.Func([], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
  'deleteUserData' : IDL.Func([], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserData)], []),
  'getAllUsersAdmin' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'streak' : IDL.Nat,
            'principal' : IDL.Text,
            'name' : IDL.Text,
            'journalCount' : IDL.Nat,
            'tasksCompleted' : IDL.Nat,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getJournalEntries' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'content' : IDL.Text,
            'date' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getProgress' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'streak' : IDL.Nat,
            'lastUpdated' : IDL.Text,
            'tasksCompleted' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getUser' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }))],
      ['query'],
    ),
  'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'saveUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveUserData' : IDL.Func([UserData], [], []),
  'searchUserByName' : IDL.Func([IDL.Text], [IDL.Opt(UserData)], ['query']),
  'updateUserStreak' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'meditation' : IDL.Bool,
    'date' : IDL.Text,
    'diet' : IDL.Bool,
    'sleep' : IDL.Bool,
    'workout' : IDL.Bool,
    'water' : IDL.Bool,
  });
  const JournalEntry = IDL.Record({
    'conquered' : IDL.Text,
    'date' : IDL.Text,
    'dominate' : IDL.Text,
  });
  const WeightEntry = IDL.Record({ 'weight' : IDL.Float64, 'date' : IDL.Text });
  const Stats = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'lastCompletedDate' : IDL.Text,
    'noExcuseMode' : IDL.Bool,
    'soundEnabled' : IDL.Bool,
  });
  const StrengthLog = IDL.Record({
    'weight' : IDL.Float64,
    'date' : IDL.Text,
    'reps' : IDL.Text,
    'sets' : IDL.Nat,
    'exercise' : IDL.Text,
  });
  const Profile = IDL.Record({
    'weight' : IDL.Text,
    'goal' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserData = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'journalEntries' : IDL.Vec(JournalEntry),
    'weightEntries' : IDL.Vec(WeightEntry),
    'stats' : Stats,
    'achievements' : IDL.Vec(IDL.Text),
    'strengthLogs' : IDL.Vec(StrengthLog),
    'profile' : Profile,
  });
  const UserProfile = IDL.Record({
    'weight' : IDL.Text,
    'goal' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllData' : IDL.Func([], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
    'deleteUserData' : IDL.Func([], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserData)], []),
    'getAllUsersAdmin' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'streak' : IDL.Nat,
              'principal' : IDL.Text,
              'name' : IDL.Text,
              'journalCount' : IDL.Nat,
              'tasksCompleted' : IDL.Nat,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getJournalEntries' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'content' : IDL.Text,
              'date' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getProgress' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'streak' : IDL.Nat,
              'lastUpdated' : IDL.Text,
              'tasksCompleted' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getUser' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }))],
        ['query'],
      ),
    'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'saveUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveUserData' : IDL.Func([UserData], [], []),
    'searchUserByName' : IDL.Func([IDL.Text], [IDL.Opt(UserData)], ['query']),
    'updateUserStreak' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };